# Generated by Django 5.0.6 on 2024-07-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='AccPriv',
            field=models.BooleanField(default=False),
        ),
    ]
