# Generated by Django 5.0.6 on 2024-07-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydoto', '0002_task_accpriv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='AccPriv',
            new_name='acc_priv',
        ),
    ]
